import './globals.css'
import { Inter, Amatic_SC } from 'next/font/google'

const amatic_SC = Amatic_SC({weight: ['400'], preload: false })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
